#!/bin/sh /etc/rc.common
# Copyright (C) 2006-2011 OpenWrt.org

START=95

SERVICE_USE_PID=1
SERVICE_WRITE_PID=1
SERVICE_DAEMONIZE=1

DEFAULT_CONFIG_FILE="/tmp/shadowsocks.json"
PROXY_EXEC="/usr/bin/ss-local"
REDIR_EXEC="/usr/bin/ss-redir"

create_config() {
    local cfg=$1
    local server server_port method timeout password

    config_get server $cfg server
    config_get server_port $cfg server_port
    config_get method $cfg method
    config_get timeout $cfg timeout
    config_get password $cfg password

    cat > $DEFAULT_CONFIG_FILE <<EOF
{
    "server":"$server",
    "server_port":$server_port,
    "password":"$password",
    "timeout":$timeout,
    "method":"$method"
}
EOF

    return 0
}

ss_start(){
    include /lib/functions

    config_load 'shadowsocks'

    local enable
    config_get_bool enable config 'enable' '0'

    if [ $enable ]; then
        local local_port redir_port addnconf

        config_get addnconf config 'addnconf'
        config_get local_port config 'local_port'
        config_get redir_port config 'redir_port'

        if [ $addnconf ] && [ -r "$addnconf" ]; then
            CONFIG_FILE=$addnconf
            echo "Use additional config file \"$CONFIG_FILE\""
        else
            create_config config
            CONFIG_FILE=$DEFAULT_CONFIG_FILE
        fi;

        [ "$local_port" ] && service_start $PROXY_EXEC -c $CONFIG_FILE -l $local_port && echo "ss-local running"
        [ "$redir_port" ] && service_start $REDIR_EXEC -c $CONFIG_FILE -l $redir_port && echo "ss-redir running"

    fi;
}


start() {
    #config_foreach ss_start shadowsocks
    stop
    ss_start

}

stop() {
    service_stop /usr/bin/ss-local
    service_stop /usr/bin/ss-redir
}
